name: terraform_todomicroapp_infra_pipeline

on: 
 push:
   branches:
   - main
   - feature/*

permissions:
  id-token: write
  contents: read

   


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout to repo
      uses: actions/checkout@v4

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: ${{secrets.AZURE_CLIENT_ID}}
        tenant-id: ${{secrets.AZURE_TENANT_ID}}
        subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

    - name: Terraform init azurerm backend
      uses: ahmedig/terraform-azurerm-backend@v4
      with: 
        client-id: ${{secrets.AZURE_CLIENT_ID}}
        tenant-id: ${{secrets.AZURE_TENANT_ID}}
        subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
        resource_group_name: backendrak-rg
        container_name: rakeshtfstg
        storage_account_name: tfstatefile
        file_name: terraform.tfstate
        path: ./environment/dev

    - name: terraform-validate    
      working-directory: ./environment/dev
      run: terraform validate

    - name: terraform-fmt    
      working-directory: ./environment/dev
      run: terraform fmt 

    - name: terraform-plan    
      working-directory: ./environment/dev
      run: terraform plan -out=tfplan

    - name: Upload Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: ./environment/dev/tfplan
        
  ManualApproval:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Approve Workflow [Manual]
      uses: trstringer/manual-approval@v1
      with:
         approvers: RakeshKSingh29
         timeout-minutes: 60
         issue-title: check the plan and approve


  apply:
    runs-on: ubuntu-latest
    needs: ManualApproval
    steps:
    - name: checkout to repo
      uses: actions/checkout@v4

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: ${{secrets.AZURE_CLIENT_ID}}
        tenant-id: ${{secrets.AZURE_TENANT_ID}}
        subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

    - name: Terraform init azurerm backend
      uses: ahmedig/terraform-azurerm-backend@v4
      with: 
        client-id: ${{secrets.AZURE_CLIENT_ID}}
        tenant-id: ${{secrets.AZURE_TENANT_ID}}
        subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
        resource_group_name: backendrak-rg
        container_name: rakeshtfstg
        storage_account_name: tfstatefile
        file_name: terraform.tfstate
        path: ./environment/dev

    - name: download plan
      uses: actions/download-artifact@v4
      with:
        name: tfplan
        path: ./environment/dev
      

    - name: terraform apply   
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      working-directory: ./environment/dev
      run: terraform apply --auto-approve tfplan

      
         
      
    
    
      

      
      
      
        
        
        
        
        
        
      
      
        
      
     
