name: terraform_todomicroapp_infra_pipeline

on: 
 pull_request:  
 push:
   branches:
   - main
   - feature/*

permissions:
  id-token: write
  contents: read

   


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout to repo
      uses: actions/checkout@v4

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: ${{secrets.AZURE_CLIENT_ID}}
        tenant-id: ${{secrets.AZURE_TENANT_ID}}
        subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

    - name: Terraform init azurerm backend
      working-directory: ./environments/dev
      run: |
        terraform init \
        -backend-config="resource_group_name=rg-terraform-backend" \
        -backend-config="storage_account_name=mytfstateaccount" \
        -backend-config="container_name=tfstate" \
        -backend-config="key=dev.terraform.tfstate"      



        

    - name: terraform-validate    
      working-directory: ./environments/dev
      run: terraform validate

    - name: terraform-fmt    
      working-directory: ./environments/dev
      run: terraform fmt 

    - name: terraform-plan    
      working-directory: ./environments/dev
      if: github.event_name == 'pull_request'
      run: terraform plan -out=tfplan

    - name: Upload Plan
      uses: actions/upload-artifact@v4
      if: github.event_name == 'pull_request'
      with:
        name: tfplan
        path: ./environments/dev/tfplan
        
  ManualApproval:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 60
    steps:
    - name: Approve Workflow [Manual]
      uses: trstringer/manual-approval@v1
      with:
         approvers: RakeshKSingh29
         secret: ${{ secrets.GITHUB_TOKEN }}
         issue-title: check the plan and approve


  apply:
    runs-on: ubuntu-latest
    needs: ManualApproval
    steps:
    - name: checkout to repo
      uses: actions/checkout@v4

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: ${{secrets.AZURE_CLIENT_ID}}
        tenant-id: ${{secrets.AZURE_TENANT_ID}}
        subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

    - name: Terraform init azurerm backend
      working-directory: ./environments/dev
      run: |
        terraform init \
        -backend-config="resource_group_name=rg-terraform-backend" \
        -backend-config="storage_account_name=mytfstateaccount" \
        -backend-config="container_name=tfstate" \
        -backend-config="key=dev.terraform.tfstate"      


    - name: download plan
      uses: actions/download-artifact@v4
      with:
        name: tfplan
        path: ./environments/dev
      

    - name: terraform apply   
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      working-directory: ./environments/dev
      run: terraform apply --auto-approve "./tfplan"
      
         
      
    
    
      

      
      
      
        
        
        
        
        
        
      
      
        
      
     
